export const medicine_inventory = {
    Paracetamol: {
        "Item_code": "PARA001",
        "category": "Medicine",
        "usage": "For pain and fever relief",
        "amp_per_item": 9,
        "expiry_date": "2024-06-30",
        "mfg_date": "2022-12-15",
        "quantity": 100,
        "unit": "tablets",
        "OR_number": "clnc-061523",
    },
    Bioflu: {
        "Item_code": "BIOF001",
        "category": "Medicine",
        "usage": "For cold and flu relief",
        "amp_per_item": 8,
        "expiry_date": "2024-11-30",
        "mfg_date": "2022-07-20",
        "quantity": 50,
        "unit": "sachets",
        "OR_number": "clnc-061523",
    },
    Biogesic: {
        "Item_code": "BIOG001",
        "category": "Medicine",
        "usage": "For pain and fever relief",
        "amp_per_item": 9,
        "expiry_date": "2024-09-30",
        "mfg_date": "2023-03-10",
        "quantity": 80,
        "unit": "tablets",
        "OR_number": "clnc-061523",
    },
    Loperamide: {
        "Item_code": "LOPE001",
        "category": "Medicine",
        "usage": "For diarrhea relief",
        "amp_per_item": 6,
        "expiry_date": "2023-08-15",
        "mfg_date": "2022-11-25",
        "quantity": 30,
        "unit": "capsules",
        "OR_number": "clnc-061523",
    },
    Advil: {
        "Item_code": "ADVL001",
        "category": "Medicine",
        "usage": "For pain and inflammation relief",
        "amp_per_item": 1,
        "expiry_date": "2024-12-31",
        "mfg_date": "2022-10-05",
        "quantity": 60,
        "unit": "tablets",
        "OR_number": "clnc-061523",
    },
    Neozep: {
        "Item_code": "NEOZ001",
        "category": "Medicine",
        "usage": "For cold and allergy relief",
        "amp_per_item": 7,
        "expiry_date": "2024-02-28",
        "mfg_date": "2023-01-15",
        "quantity": 40,
        "unit": "tablets",
        "OR_number": "clnc-061523",
    },
    Enervon: {
        "Item_code": "ENER001",
        "category": "Medicine",
        "usage": "For vitamin supplementation",
        "amp_per_item": 8,
        "expiry_date": "2024-04-30",
        "mfg_date": "2023-02-10",
        "quantity": 90,
        "unit": "tablets",
        "OR_number": "clnc-061523",
    },
    Gaviscon: {
        "Item_code": "GAVI001",
        "category": "Medicine",
        "usage": "For heartburn and acid reflux relief",
        "amp_per_item": 9,
        "expiry_date": "2024-03-31",
        "mfg_date": "2023-01-05",
        "quantity": 70,
        "unit": "tablets",
        "OR_number": "clnc-061523",
    },
    Chocolate: {
        "Item_code": "CHOC001",
        "category": "Food",
        "usage": "For consumption",
        "amp_per_item": 5,
        "expiry_date": "2024-09-15",
        "mfg_date": "2022-07-01",
        "quantity": 10,
        "unit": "bars",
    },
    Band_aid: {
        "Item_code": "BAND001",
        "category": "Medical Supplies",
        "usage": "For wound protection",
        "amp_per_item": 3,
        "expiry_date": "2025-01-31",
        "mfg_date": "2023-06-20",
        "quantity": 200,
        "unit": "pieces",
        "OR_number": "clnc-061523",
    },
    Alcohol: {
        "Item_code": "ALCO001",
        "category": "Medical Supplies",
        "usage": "For disinfection",
        "amp_per_item": 10,
        "expiry_date": "2024-07-31",
        "mfg_date": "2023-01-10",
        "quantity": 500,
        "unit": "ml",
        "OR_number": "clnc-061523",
    },
    Betadine: {
        "Item_code": "BETA001",
        "category": "Medical Supplies",
        "usage": "For wound disinfection",
        "amp_per_item": 6,
        "expiry_date": "2024-11-30",
        "mfg_date": "2022-09-15",
        "quantity": 100,
        "unit": "ml",
        "OR_number": "clnc-061523",
    },
    Cotton_Ball: {
        "Item_code": "COTT001",
        "category": "Medical Supplies",
        "usage": "For wound cleaning",
        "amp_per_item": 3,
        "expiry_date": "2024-12-31",
        "mfg_date": "2023-02-01",
        "quantity": 300,
        "unit": "balls",
        "OR_number": "clnc-061523",
    },
    Micropore: {
        "Item_code": "MICR001",
        "category": "Medical Supplies",
        "usage": "For wound dressing",
        "amp_per_item": 8,
        "expiry_date": "2024-11-15",
        "mfg_date": "2022-09-10",
        "quantity": 5,
        "unit": "rolls",
        "OR_number": "clnc-061523",
    },
    Gauze: {
        "Item_code": "GAUZ001",
        "category": "Medical Supplies",
        "usage": "For wound dressing",
        "amp_per_item": 9,
        "expiry_date": "2024-10-31",
        "mfg_date": "2022-12-15",
        "quantity": 10,
        "unit": "pieces",
        "OR_number": "clnc-061523",
    },
}

